# -*- coding: utf-8 -*-
"""100th monkey maker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17iAMC3YQVany08Eo4R8144BiFw1eJCHe
"""

# app.py
import streamlit as st
import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter

# ---------- SETTINGS ----------
W, H = 800, 300
FONT_SIZE = 200

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# ---------- RENDER ----------
def render(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0,0), word, font=f)
    x = (W - (bbox[2]-bbox[0]))//2
    y = (H - (bbox[3]-bbox[1]))//2
    d.text((x,y), word, 0, font=f)
    return np.array(img) / 255.0

def generate_image(near_word, far_word):
    BG_GRAY = 0.9

    NEAR_EDGE_STRENGTH = 0.85
    NEAR_EDGE_BLUR = 2.0
    NEAR_DISTANCE_BLUR = 5.0
    NEAR_PERSISTENCE = 0.75

    FAR_BLUR_SIGMA = 14.5
    FAR_INK_STRENGTH = 0.48
    FAR_DETAIL_BOOST = 0.22
    FAR_SUPPRESSION = 0.60

    BG_CLOUD_STRENGTH = 0.09
    BG_SCALES = [20.0, 60.0, 160.0]
    BG_WEIGHTS = [0.4, 0.35, 0.25]

    near_img = render(near_word, FONT_NEAR)
    far_img  = render(far_word,  FONT_FAR)

    noise = np.random.randn(H, W)
    clouds = np.zeros_like(noise)
    for w, s in zip(BG_WEIGHTS, BG_SCALES):
        clouds += w * gaussian_filter(noise, s)
    clouds /= np.std(clouds)
    clouds = np.tanh(clouds * 0.9)

    bg = np.clip(BG_GRAY + BG_CLOUD_STRENGTH * clouds, 0, 1)

    near_edges = np.clip(
        near_img - gaussian_filter(near_img, NEAR_EDGE_BLUR),
        0, 1
    )
    near_edges_blurred = gaussian_filter(near_edges, NEAR_DISTANCE_BLUR)
    near_ink = NEAR_EDGE_STRENGTH * (
        NEAR_PERSISTENCE * near_edges +
        (1 - NEAR_PERSISTENCE) * near_edges_blurred
    )

    far_base = 1 - gaussian_filter(far_img, FAR_BLUR_SIGMA)
    far_mid = gaussian_filter(far_base, 4.0) - gaussian_filter(far_base, 10.0)
    far_mid = np.clip(far_mid, 0, 1)
    far_ink = FAR_INK_STRENGTH * FAR_SUPPRESSION * (
        far_base + FAR_DETAIL_BOOST * far_mid
    )

    out = np.clip(bg - (near_ink + far_ink), 0, 1)
    return Image.fromarray((out * 255).astype("uint8"))

# ---------- STREAMLIT UI ----------
st.set_page_config(layout="wide")

st.title("Perceptual Depth Words")

near = st.text_input("Near word", "Shimon")
far  = st.text_input("Far word", "Michal")

img = generate_image(near, far)
st.image(img, use_column_width=True)

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt

# ---------- SETTINGS ----------
W, H = 1400, 300
FONT_SIZE = 200

NEAR_WORD = "Qxprgtsdwxfs"
FAR_WORD  = "Chana Golda"
# NEAR_WORD = "Qxpsrgtsdf"
# FAR_WORD  = "Yaniv Ilan"

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# ---------- PERCEPTUAL PARAMETERS ----------
BG_GRAY = 0.9

# Near word (unchanged, correct)
NEAR_EDGE_STRENGTH = 0.7
NEAR_EDGE_BLUR     = 2.0
NEAR_DISTANCE_BLUR = 5.0
NEAR_PERSISTENCE   = 0.75

# Far word (FIXED BALANCE)
FAR_BLUR_SIGMA     = 14.0     # ↓ less blur
FAR_INK_STRENGTH   = 0.8     # ↑ slightly stronger
FAR_DETAIL_BOOST   = 0.3     # mid-scale only
FAR_SUPPRESSION    = 0.6     # ↓ less suppression

# Background cloudiness
BG_CLOUD_STRENGTH = 0.15
BG_SCALES  = [20.0, 60.0, 160.0]
BG_WEIGHTS = [0.4, 0.35, 0.25]

# ---------- RENDER ----------
def render(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0,0), word, font=f)
    x = (W - (bbox[2]-bbox[0]))//2
    y = (H - (bbox[3]-bbox[1]))//2
    d.text((x,y), word, 0, font=f)
    return np.array(img) / 255.0

near_img = render(NEAR_WORD, FONT_NEAR)
far_img  = render(FAR_WORD,  FONT_FAR)

# ---------- BUSY CLOUDY BACKGROUND ----------
np.random.seed(2)
noise = np.random.randn(H, W)

clouds = np.zeros_like(noise)
for w, s in zip(BG_WEIGHTS, BG_SCALES):
    clouds += w * gaussian_filter(noise, s)

clouds /= np.std(clouds)
clouds = np.tanh(clouds * 0.9)

bg = BG_GRAY + BG_CLOUD_STRENGTH * clouds
bg = np.clip(bg, 0, 1)

# ---------- NEAR WORD ----------
near_edges = np.clip(
    near_img - gaussian_filter(near_img, NEAR_EDGE_BLUR),
    0, 1
)

near_edges_blurred = gaussian_filter(near_edges, NEAR_DISTANCE_BLUR)

near_ink = NEAR_EDGE_STRENGTH * (
    NEAR_PERSISTENCE * near_edges +
    (1 - NEAR_PERSISTENCE) * near_edges_blurred
)

# ---------- FAR WORD (mid-scale structure, not mush) ----------
far_base = 1 - gaussian_filter(far_img, FAR_BLUR_SIGMA)

# mid-frequency structure (not fine edges)
far_mid = gaussian_filter(far_base, 4.0) - gaussian_filter(far_base, 10.0)
far_mid = np.clip(far_mid, 0, 1)

far_ink = FAR_INK_STRENGTH * FAR_SUPPRESSION * (
    far_base + FAR_DETAIL_BOOST * far_mid
)

# ---------- COMPOSITE ----------
out = bg - (near_ink + far_ink)
out = np.clip(out, 0, 1)

# ---------- DISPLAY ----------
plt.figure(figsize=(10, 4))
plt.imshow(out, cmap="gray", vmin=0, vmax=1)
plt.axis("off")
plt.show()



import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt

# ---------- SETTINGS ----------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "Shimon"
FAR_WORD  = "Michal"

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# ---------- PERCEPTUAL PARAMETERS ----------
BG_GRAY = 0.9

# Near word
NEAR_EDGE_STRENGTH = 0.85
NEAR_EDGE_BLUR     = 2.0
NEAR_DISTANCE_BLUR = 5.0
NEAR_PERSISTENCE   = 0.75

# Far word (slightly sharper)
FAR_BLUR_SIGMA     = 14.0   # ↓ was 18.0
FAR_INK_STRENGTH   = 0.55
FAR_DETAIL_BOOST   = 0.25   # <<< new (very gentle)

# Background cloudiness
BG_CLOUD_STRENGTH = 0.09
BG_SCALES  = [20.0, 60.0, 160.0]
BG_WEIGHTS = [0.4, 0.35, 0.25]

# ---------- RENDER ----------
def render(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0,0), word, font=f)
    x = (W - (bbox[2]-bbox[0]))//2
    y = (H - (bbox[3]-bbox[1]))//2
    d.text((x,y), word, 0, font=f)
    return np.array(img) / 255.0

near_img = render(NEAR_WORD, FONT_NEAR)
far_img  = render(FAR_WORD,  FONT_FAR)

# ---------- BUSY CLOUDY BACKGROUND ----------
np.random.seed(2)
noise = np.random.randn(H, W)

clouds = np.zeros_like(noise)
for w, s in zip(BG_WEIGHTS, BG_SCALES):
    clouds += w * gaussian_filter(noise, s)

clouds /= np.std(clouds)
clouds = np.tanh(clouds * 0.9)

bg = BG_GRAY + BG_CLOUD_STRENGTH * clouds
bg = np.clip(bg, 0, 1)

# ---------- NEAR WORD ----------
near_edges = np.clip(
    near_img - gaussian_filter(near_img, NEAR_EDGE_BLUR),
    0, 1
)

near_edges_blurred = gaussian_filter(near_edges, NEAR_DISTANCE_BLUR)

near_ink = NEAR_EDGE_STRENGTH * (
    NEAR_PERSISTENCE * near_edges +
    (1 - NEAR_PERSISTENCE) * near_edges_blurred
)

# ---------- FAR WORD (slightly sharper, still distant) ----------
far_base = 1 - gaussian_filter(far_img, FAR_BLUR_SIGMA)

# very gentle detail recovery
far_detail = np.clip(
    far_base - gaussian_filter(far_base, 6.0),
    0, 1
)

far_ink = FAR_INK_STRENGTH * (
    far_base + FAR_DETAIL_BOOST * far_detail
)

# ---------- COMPOSITE ----------
out = bg - (near_ink + far_ink)
out = np.clip(out, 0, 1)

# ---------- DISPLAY ----------
plt.figure(figsize=(10, 4))
plt.imshow(out, cmap="gray", vmin=0, vmax=1)
plt.axis("off")
plt.title("Perceived View (Distance)")
plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt

# ---------- SETTINGS ----------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "Shimon"
FAR_WORD  = "Michal"

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# ---------- PERCEPTUAL PARAMETERS ----------
BG_GRAY = 0.9

# Near word
NEAR_EDGE_STRENGTH = 0.85
NEAR_EDGE_BLUR     = 2.0
NEAR_DISTANCE_BLUR = 5.0
NEAR_PERSISTENCE   = 0.75

# Far word
FAR_BLUR_SIGMA   = 18.0
FAR_INK_STRENGTH = 0.55

# Background cloudiness (ENHANCED)
BG_CLOUD_STRENGTH = 0.09
BG_SCALES = [20.0, 60.0, 160.0]   # fine → medium → large
BG_WEIGHTS = [0.4, 0.35, 0.25]

# ---------- RENDER ----------
def render(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0,0), word, font=f)
    x = (W - (bbox[2]-bbox[0]))//2
    y = (H - (bbox[3]-bbox[1]))//2
    d.text((x,y), word, 0, font=f)
    return np.array(img) / 255.0

near_img = render(NEAR_WORD, FONT_NEAR)
far_img  = render(FAR_WORD,  FONT_FAR)

# ---------- BUSY CLOUDY BACKGROUND ----------
np.random.seed(2)
noise = np.random.randn(H, W)

clouds = np.zeros_like(noise)
for w, s in zip(BG_WEIGHTS, BG_SCALES):
    clouds += w * gaussian_filter(noise, s)

clouds /= np.std(clouds)

# Gentle contrast curve (adds richness without harshness)
clouds = np.tanh(clouds * 0.9)

bg = BG_GRAY + BG_CLOUD_STRENGTH * clouds
bg = np.clip(bg, 0, 1)

# ---------- NEAR WORD ----------
near_edges = np.clip(
    near_img - gaussian_filter(near_img, NEAR_EDGE_BLUR),
    0, 1
)

near_edges_blurred = gaussian_filter(near_edges, NEAR_DISTANCE_BLUR)

near_ink = NEAR_EDGE_STRENGTH * (
    NEAR_PERSISTENCE * near_edges +
    (1 - NEAR_PERSISTENCE) * near_edges_blurred
)

# ---------- FAR WORD ----------
far_mass = 1 - gaussian_filter(far_img, FAR_BLUR_SIGMA)
far_ink  = FAR_INK_STRENGTH * far_mass

# ---------- COMPOSITE ----------
out = bg - (near_ink + far_ink)
out = np.clip(out, 0, 1)

# ---------- DISPLAY ----------
plt.figure(figsize=(10, 4))
plt.imshow(out, cmap="gray", vmin=0, vmax=1)
plt.axis("off")
plt.title("Perceived View (Distance)")
plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt

# ---------- SETTINGS ----------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "Shimon"
FAR_WORD  = "Michal"

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# ---------- PERCEPTUAL PARAMETERS ----------
BG_GRAY = 0.9

# Near word
NEAR_EDGE_STRENGTH = 0.85
NEAR_EDGE_BLUR     = 2.0
NEAR_DISTANCE_BLUR = 5.0
NEAR_PERSISTENCE   = 0.75

# Far word
FAR_BLUR_SIGMA   = 18.0
FAR_INK_STRENGTH = 0.55

# Background cloudiness
BG_CLOUD_STRENGTH = 0.06
BG_CLOUD_SCALE_1  = 40.0
BG_CLOUD_SCALE_2  = 120.0

# ---------- RENDER ----------
def render(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0,0), word, font=f)
    x = (W - (bbox[2]-bbox[0]))//2
    y = (H - (bbox[3]-bbox[1]))//2
    d.text((x,y), word, 0, font=f)
    return np.array(img) / 255.0

near_img = render(NEAR_WORD, FONT_NEAR)
far_img  = render(FAR_WORD,  FONT_FAR)

# ---------- CLOUDY BACKGROUND ----------
np.random.seed(1)
noise = np.random.randn(H, W)

cloud_low  = gaussian_filter(noise, BG_CLOUD_SCALE_2)
cloud_mid  = gaussian_filter(noise, BG_CLOUD_SCALE_1)

clouds = 0.6 * cloud_low + 0.4 * cloud_mid
clouds = clouds / np.std(clouds)

bg = BG_GRAY + BG_CLOUD_STRENGTH * clouds
bg = np.clip(bg, 0, 1)

# ---------- NEAR WORD ----------
near_edges = np.clip(
    near_img - gaussian_filter(near_img, NEAR_EDGE_BLUR),
    0, 1
)

near_edges_blurred = gaussian_filter(near_edges, NEAR_DISTANCE_BLUR)

near_ink = NEAR_EDGE_STRENGTH * (
    NEAR_PERSISTENCE * near_edges +
    (1 - NEAR_PERSISTENCE) * near_edges_blurred
)

# ---------- FAR WORD ----------
far_mass = 1 - gaussian_filter(far_img, FAR_BLUR_SIGMA)
far_ink  = FAR_INK_STRENGTH * far_mass

# ---------- COMPOSITE ----------
out = bg - (near_ink + far_ink)
out = np.clip(out, 0, 1)

# ---------- DISPLAY ----------
plt.figure(figsize=(10, 4))
plt.imshow(out, cmap="gray", vmin=0, vmax=1)
plt.axis("off")
plt.title("Perceived View (Distance)")
plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt

# ---------- SETTINGS ----------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "Shimon"
FAR_WORD  = "Michal"

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# ---------- PERCEPTUAL PARAMETERS ----------
BG_GRAY = 0.9

# Near word (edge-privileged, distance blurred but persistent)
NEAR_EDGE_STRENGTH = 0.85
NEAR_EDGE_BLUR     = 2.0
NEAR_DISTANCE_BLUR = 5.0
NEAR_PERSISTENCE   = 0.75   # <<< key fix

# Far word (diffuse, never sharp)
FAR_BLUR_SIGMA   = 18.0
FAR_INK_STRENGTH = 0.55

# ---------- RENDER ----------
def render(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0,0), word, font=f)
    x = (W - (bbox[2]-bbox[0]))//2
    y = (H - (bbox[3]-bbox[1]))//2
    d.text((x,y), word, 0, font=f)
    return np.array(img) / 255.0

near_img = render(NEAR_WORD, FONT_NEAR)
far_img  = render(FAR_WORD,  FONT_FAR)

# ---------- NEAR WORD (edge-preserving distance perception) ----------
# Extract edges
near_edges = np.clip(
    near_img - gaussian_filter(near_img, NEAR_EDGE_BLUR),
    0, 1
)

# Distance blur (acuity loss)
near_edges_blurred = gaussian_filter(near_edges, NEAR_DISTANCE_BLUR)

# Edge persistence (THIS is what was missing)
near_ink = NEAR_EDGE_STRENGTH * (
    NEAR_PERSISTENCE * near_edges +
    (1 - NEAR_PERSISTENCE) * near_edges_blurred
)

# ---------- FAR WORD (diffuse mass only) ----------
far_mass = 1 - gaussian_filter(far_img, FAR_BLUR_SIGMA)
far_ink  = FAR_INK_STRENGTH * far_mass

# ---------- COMPOSITE ----------
out = BG_GRAY - (near_ink + far_ink)
out = np.clip(out, 0, 1)

# ---------- DISPLAY ----------
plt.figure(figsize=(10, 4))
plt.imshow(out, cmap="gray", vmin=0, vmax=1)
plt.axis("off")
plt.title("")
plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt

# ---------- SETTINGS ----------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "Shimon"
FAR_WORD  = "Michal"

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# ---------- PERCEPTUAL PARAMETERS ----------
BG_GRAY = 0.9

# Near word (still visible far away, but blurred)
NEAR_EDGE_STRENGTH = 0.7
NEAR_DISTANCE_BLUR = 6.0
NEAR_DISTANCE_FADE = 0.6

# Far word (never perfectly sharp)
FAR_BLUR_SIGMA     = 18.0
FAR_INK_STRENGTH   = 0.55

# ---------- RENDER ----------
def render(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0,0), word, font=f)
    x = (W - (bbox[2]-bbox[0]))//2
    y = (H - (bbox[3]-bbox[1]))//2
    d.text((x,y), word, 0, font=f)
    return np.array(img) / 255.0

near_img = render(NEAR_WORD, FONT_NEAR)
far_img  = render(FAR_WORD,  FONT_FAR)

# ---------- PERCEPTION MODEL ----------
# Near word: edges → then blurred by distance
near_edges = np.clip(near_img - gaussian_filter(near_img, 2.0), 0, 1)
near_edges = gaussian_filter(near_edges, NEAR_DISTANCE_BLUR)
near_ink   = NEAR_EDGE_STRENGTH * NEAR_DISTANCE_FADE * near_edges

# Far word: diffuse mass only (never sharp)
far_mass = 1 - gaussian_filter(far_img, FAR_BLUR_SIGMA)
far_ink  = FAR_INK_STRENGTH * far_mass

# Composite on gray paper
out = BG_GRAY - (near_ink + far_ink)
out = np.clip(out, 0, 1)

# ---------- DISPLAY ----------
plt.figure(figsize=(10, 4))
plt.imshow(out, cmap="gray", vmin=0, vmax=1)
plt.axis("off")
plt.title("Perceived View (Distance)")
plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt

# ---------- SETTINGS ----------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "Shimon"
FAR_WORD  = "Michal"

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# ---------- INITIAL PARAMETERS ----------
NEAR_EDGE_STRENGTH = 0.75
FAR_BLUR_SIGMA     = 20.0
FAR_INK_STRENGTH   = 0.5
VIEW_BLUR_SIGMA    = 7.0
BG_GRAY            = 0.9

# ---------- RENDER ----------
def render(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0,0), word, font=f)
    x = (W - (bbox[2]-bbox[0]))//2
    y = (H - (bbox[3]-bbox[1]))//2
    d.text((x,y), word, 0, font=f)
    return np.array(img)/255.0

near_img = render(NEAR_WORD, FONT_NEAR)
far_img  = render(FAR_WORD,  FONT_FAR)

# ---------- FIGURE (NEAR VIEW ONLY) ----------
fig, ax_main = plt.subplots(figsize=(10, 4))
img_main = ax_main.imshow(np.ones((H, W)), cmap="gray", vmin=0, vmax=1)
ax_main.set_title("Near View")
ax_main.axis("off")

# ---------- UPDATE ----------
def update():
    # NEAR: dark edges only
    near_blur = gaussian_filter(near_img, sigma=2.0)
    near_hp   = np.clip(near_img - near_blur, 0, 1)
    near_ink  = NEAR_EDGE_STRENGTH * near_hp

    # FAR: still contributes to composite (unchanged)
    far_lp   = gaussian_filter(far_img, sigma=FAR_BLUR_SIGMA)
    far_ink  = FAR_INK_STRENGTH * (1 - far_lp)

    # COMPOSITE ON GRAY PAPER
    out = BG_GRAY - (near_ink + far_ink)
    out = np.clip(out, 0, 1)

    img_main.set_data(out)
    fig.canvas.draw_idle()

# ---------- DRAW ----------
update()
plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider

# ---------- SETTINGS ----------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "Shimon"
FAR_WORD  = "Michal"

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# ---------- INITIAL PARAMETERS ----------
NEAR_EDGE_STRENGTH = 0.75
FAR_BLUR_SIGMA     = 20.0
FAR_INK_STRENGTH   = 0.5
VIEW_BLUR_SIGMA    = 7.0
BG_GRAY            = 0.9   # <<< BACKGROUND GRAY LEVEL (0=black, 1=white)

# ---------- RENDER ----------
def render(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0,0), word, font=f)
    x = (W - (bbox[2]-bbox[0]))//2
    y = (H - (bbox[3]-bbox[1]))//2
    d.text((x,y), word, 0, font=f)
    return np.array(img)/255.0

near_img = render(NEAR_WORD, FONT_NEAR)
far_img  = render(FAR_WORD,  FONT_FAR)

# ---------- FIGURE ----------
fig, (ax_main, ax_far) = plt.subplots(2, 1, figsize=(10, 6))
plt.subplots_adjust(left=0.15, bottom=0.32)

img_main = ax_main.imshow(np.ones((H, W)), cmap="gray", vmin=0, vmax=1)
ax_main.set_title("Near View")
ax_main.axis("off")

img_far = ax_far.imshow(np.ones((H, W)), cmap="gray", vmin=0, vmax=1)
ax_far.set_title("Far View")
ax_far.axis("off")

# ---------- UPDATE ----------
def update(val=None):
    # NEAR: dark edges only
    near_blur = gaussian_filter(near_img, sigma=2.0)
    near_hp   = np.clip(near_img - near_blur, 0, 1)
    near_ink  = NEAR_EDGE_STRENGTH * near_hp

    # FAR: dark diffuse mass
    far_lp   = gaussian_filter(far_img, sigma=FAR_BLUR_SIGMA)
    far_ink  = FAR_INK_STRENGTH * (1 - far_lp)

    # COMPOSITE ON GRAY PAPER
    out = BG_GRAY - (near_ink + far_ink)
    out = np.clip(out, 0, 1)

    img_main.set_data(out)
    img_far.set_data(gaussian_filter(out, VIEW_BLUR_SIGMA))
    fig.canvas.draw_idle()

# ---------- SLIDERS ----------
axes = {
    "Near Strength": (0.5, 1.2, NEAR_EDGE_STRENGTH),
    "Far Blur":      (6.0, 18.0, FAR_BLUR_SIGMA),
    "Far Strength":  (0.4, 1.2, FAR_INK_STRENGTH),
    "View Blur":     (4.0, 10.0, VIEW_BLUR_SIGMA),
    "BG Gray":       (0.6, 0.95, BG_GRAY),
}

sliders = {}
y = 0.25
for name, (a, b, v) in axes.items():
    ax = plt.axes([0.15, y, 0.7, 0.02])
    sliders[name] = Slider(ax, name, a, b, valinit=v)
    y -= 0.035

def on_change(val):
    global NEAR_EDGE_STRENGTH, FAR_BLUR_SIGMA, FAR_INK_STRENGTH, VIEW_BLUR_SIGMA, BG_GRAY
    NEAR_EDGE_STRENGTH = sliders["Near Strength"].val
    FAR_BLUR_SIGMA     = sliders["Far Blur"].val
    FAR_INK_STRENGTH   = sliders["Far Strength"].val
    VIEW_BLUR_SIGMA    = sliders["View Blur"].val
    BG_GRAY            = sliders["BG Gray"].val
    update()

for s in sliders.values():
    s.on_changed(on_change)

# ---------- DRAW ----------
update()
plt.show()

# @title
import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider

# ---------- SETTINGS ----------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "Country"
FAR_WORD  = "Canada"

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# ---------- INITIAL PARAMETERS ----------
NEAR_EDGE_STRENGTH = 0.75
FAR_BLUR_SIGMA     = 20.0
FAR_INK_STRENGTH   = 0.5
VIEW_BLUR_SIGMA    = 7.0
BG_GRAY            = 0.9   # logical background brightness

# ---------- COLOR SETTINGS ----------
# Background color (spacey blue-purple)
BG_COLOR = np.array([0.25, 0.22, 0.40])   # RGB in [0,1]

# Ink color (lighter blue/purple glow)
INK_COLOR = np.array([0.65, 0.55, 0.85])  # RGB in [0,1]

# ---------- RENDER ----------
def render(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0,0), word, font=f)
    x = (W - (bbox[2]-bbox[0]))//2
    y = (H - (bbox[3]-bbox[1]))//2
    d.text((x,y), word, 0, font=f)
    return np.array(img)/255.0

near_img = render(NEAR_WORD, FONT_NEAR)
far_img  = render(FAR_WORD,  FONT_FAR)

# ---------- FIGURE ----------
fig, (ax_main, ax_far) = plt.subplots(2, 1, figsize=(10, 6))
plt.subplots_adjust(left=0.15, bottom=0.32)

img_main = ax_main.imshow(np.zeros((H, W, 3)))
ax_main.set_title("Near View")
ax_main.axis("off")

img_far = ax_far.imshow(np.zeros((H, W, 3)))
ax_far.set_title("Far View")
ax_far.axis("off")

# ---------- UPDATE ----------
def update(val=None):
    # NEAR: dark edges only
    near_blur = gaussian_filter(near_img, sigma=2.0)
    near_hp   = np.clip(near_img - near_blur, 0, 1)
    near_ink  = NEAR_EDGE_STRENGTH * near_hp

    # FAR: dark diffuse mass
    far_lp   = gaussian_filter(far_img, sigma=FAR_BLUR_SIGMA)
    far_ink  = FAR_INK_STRENGTH * (1 - far_lp)

    # Logical grayscale composite
    gray = BG_GRAY - (near_ink + far_ink)
    gray = np.clip(gray, 0, 1)

    # -------- COLORIZE --------
    # Mix background color with ink color using grayscale as mask
    color = (
        BG_COLOR[None,None,:] * gray[:,:,None] +
        INK_COLOR[None,None,:] * (1 - gray[:,:,None])
    )

    img_main.set_data(color)
    img_far.set_data(gaussian_filter(color, (VIEW_BLUR_SIGMA, VIEW_BLUR_SIGMA, 0)))
    fig.canvas.draw_idle()

# ---------- SLIDERS ----------
axes = {
    "Near Strength": (0.5, 1.2, NEAR_EDGE_STRENGTH),
    "Far Blur":      (6.0, 30.0, FAR_BLUR_SIGMA),
    "Far Strength":  (0.2, 1.0, FAR_INK_STRENGTH),
    "View Blur":     (4.0, 12.0, VIEW_BLUR_SIGMA),
    "BG Gray":       (0.6, 0.95, BG_GRAY),
}

sliders = {}
y = 0.25
for name, (a, b, v) in axes.items():
    ax = plt.axes([0.15, y, 0.7, 0.02])
    sliders[name] = Slider(ax, name, a, b, valinit=v)
    y -= 0.035

def on_change(val):
    global NEAR_EDGE_STRENGTH, FAR_BLUR_SIGMA, FAR_INK_STRENGTH, VIEW_BLUR_SIGMA, BG_GRAY
    NEAR_EDGE_STRENGTH = sliders["Near Strength"].val
    FAR_BLUR_SIGMA     = sliders["Far Blur"].val
    FAR_INK_STRENGTH   = sliders["Far Strength"].val
    VIEW_BLUR_SIGMA    = sliders["View Blur"].val
    BG_GRAY            = sliders["BG Gray"].val
    update()

for s in sliders.values():
    s.on_changed(on_change)

# ---------- DRAW ----------
update()
plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt

# ---------- SETTINGS ----------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "Month"
FAR_WORD  = "March"

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

NEAR_EDGE_STRENGTH = 0.3
FAR_BLUR_SIGMA     = 11.0
FAR_INK_STRENGTH   = 0.1
VIEW_BLUR_SIGMA    = 15.0

# ---------- RENDER ----------
def render(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0,0), word, font=f)
    x = (W - (bbox[2]-bbox[0]))//2
    y = (H - (bbox[3]-bbox[1]))//2
    d.text((x,y), word, 0, font=f)
    return np.array(img)/255.0  # 0=black, 1=white

near_img = render(NEAR_WORD, FONT_NEAR)
far_img  = render(FAR_WORD,  FONT_FAR)

# ---------- NEAR: HIGH-PASS DARK EDGES ----------
near_blur = gaussian_filter(near_img, sigma=2.0)
near_hp   = np.clip(near_img - near_blur, 0, 1)
near_ink  = NEAR_EDGE_STRENGTH * near_hp

# ---------- FAR: LOW-PASS DARK MASS ----------
far_lp   = gaussian_filter(far_img, sigma=FAR_BLUR_SIGMA)
far_ink  = FAR_INK_STRENGTH * (1 - far_lp)  # <<< POLARITY FIX

# ---------- COMPOSITE (DARK INK ON WHITE) ----------
out = np.clip(1 - (near_ink + far_ink), 0, 1)

# ---------- DISPLAY ----------
plt.figure(figsize=(10,4))
plt.imshow(out, cmap="gray")
plt.axis("off")
plt.title("Composite (Near View)")
plt.show()

plt.figure(figsize=(10,4))
plt.imshow(gaussian_filter(out, VIEW_BLUR_SIGMA), cmap="gray")
plt.axis("off")
plt.title("Simulated Far View")
plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt

# ---------- SETTINGS ----------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "MONTH"
FAR_WORD  = "MARCH"

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# ---- perception knobs (ONLY THESE MATTER) ----
NEAR_EDGE_STRENGTH = 0.9   # visibility up close
FAR_BLUR_SIGMA     = 12.0  # how unreadable FAR is up close
FAR_STRENGTH       = 0.9   # visibility from far
VIEW_BLUR_SIGMA    = 6.0   # simulate distance

# ---------- RENDER ----------
def render(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0,0), word, font=f)
    x = (W - (bbox[2]-bbox[0]))//2
    y = (H - (bbox[3]-bbox[1]))//2
    d.text((x,y), word, 0, font=f)
    return np.array(img)/255.0

near_img = render(NEAR_WORD, FONT_NEAR)
far_img  = render(FAR_WORD,  FONT_FAR)

# ---------- NEAR = HIGH-PASS (EDGES ONLY) ----------
near_blur = gaussian_filter(near_img, sigma=2.0)
near_hp   = np.clip(near_blur - near_img, 0, 1)
near_hp   = NEAR_EDGE_STRENGTH * near_hp

# ---------- FAR = LOW-PASS (MASS ONLY) ----------
far_lp = gaussian_filter(far_img, sigma=FAR_BLUR_SIGMA)
far_lp = FAR_STRENGTH * far_lp

# ---------- COMPOSITE ----------
out = np.clip(1 - (near_hp + far_lp), 0, 1)

# ---------- DISPLAY ----------
plt.figure(figsize=(10,4))
plt.imshow(out, cmap="gray")
plt.axis("off")
plt.title("Composite (Near View)")
plt.show()

plt.figure(figsize=(10,4))
plt.imshow(gaussian_filter(out, VIEW_BLUR_SIGMA), cmap="gray")
plt.axis("off")
plt.title("Simulated Far View")
plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt, gaussian_filter
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider

# ================= CANVAS =================
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "MONTH"
FAR_WORD  = "MARCH"

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# ================= HELPERS =================
def render_mask(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0, 0), word, font=f)
    x = (W - (bbox[2] - bbox[0])) // 2
    y = (H - (bbox[3] - bbox[1])) // 2
    d.text((x, y), word, 0, font=f)
    return (np.array(img) < 128)

# ================= MASKS =================
mask_near = render_mask(NEAR_WORD, FONT_NEAR)
mask_far  = render_mask(FAR_WORD, FONT_FAR)

dist_near = distance_transform_edt(mask_near)
dist_near /= dist_near.max()
edge_dist = 1 - dist_near

dist_far = distance_transform_edt(mask_far)
dist_far /= dist_far.max()

# ================= INITIAL PRESET =================
EDGE_POWER  = 6.5
EDGE_INK    = 0.45
NEAR_SCALE  = 0.75

SPINE_POWER = 2.2
SPINE_INK   = 0.55   # slightly stronger FAR

FAR_BLUR    = 10.0
VIEW_BLUR   = 6.0

# ================= FIGURE =================
fig, (ax_main, ax_far) = plt.subplots(2, 1, figsize=(10, 6))
plt.subplots_adjust(left=0.15, bottom=0.35)

img_main = ax_main.imshow(np.ones((H, W)), cmap="gray", vmin=0, vmax=1)
ax_main.set_title("Near View (MONTH)")
ax_main.axis("off")

img_far = ax_far.imshow(np.ones((H, W)), cmap="gray", vmin=0, vmax=1)
ax_far.set_title("Far View (MARCH)")
ax_far.axis("off")

# ================= UPDATE =================
def update(val=None):
    # ----- NEAR: HIGH-PASS ONLY -----
    near_val = 1 - EDGE_INK * (edge_dist ** EDGE_POWER)
    near_low = gaussian_filter(near_val, sigma=3.0)
    near_val = np.clip(near_val - near_low + 1.0, 0, 1)  # remove low freq

    # ----- FAR: LOW-FREQ MASS -----
    far_val = 1 - SPINE_INK * (dist_far ** SPINE_POWER)
    far_val = gaussian_filter(far_val, sigma=FAR_BLUR)
    far_val = 1 - 0.5 * (1 - far_val)  # contrast compression

    out = np.ones((H, W))
    out[mask_far]  -= (1 - far_val[mask_far])
    out[mask_near] -= NEAR_SCALE * (1 - near_val[mask_near])
    out = np.clip(out, 0, 1)

    img_main.set_data(out)
    img_far.set_data(gaussian_filter(out, sigma=VIEW_BLUR))
    fig.canvas.draw_idle()

# ================= SLIDERS =================
axes = {
    "Near Scale":      (0.4, 0.9, NEAR_SCALE),
    "Far Blur":        (6.0, 16.0, FAR_BLUR),
    "Far Ink":         (0.4, 0.7, SPINE_INK),
    "View Blur":       (4.0, 10.0, VIEW_BLUR),
}

sliders = {}
y = 0.28
for name, (a, b, v) in axes.items():
    ax = plt.axes([0.15, y, 0.7, 0.02])
    sliders[name] = Slider(ax, name, a, b, valinit=v)
    y -= 0.04

def on_change(val):
    global NEAR_SCALE, FAR_BLUR, SPINE_INK, VIEW_BLUR
    NEAR_SCALE = sliders["Near Scale"].val
    FAR_BLUR   = sliders["Far Blur"].val
    SPINE_INK  = sliders["Far Ink"].val
    VIEW_BLUR  = sliders["View Blur"].val
    update()

for s in sliders.values():
    s.on_changed(on_change)

# ================= DRAW =================
update()
plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt, gaussian_filter
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider

# ================= CANVAS =================
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "MONTH"
FAR_WORD  = "MARCH"

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# ================= HELPERS =================
def render_mask(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0, 0), word, font=f)
    x = (W - (bbox[2] - bbox[0])) // 2
    y = (H - (bbox[3] - bbox[1])) // 2
    d.text((x, y), word, 0, font=f)
    return (np.array(img) < 128)

# ================= MASKS =================
mask_near = render_mask(NEAR_WORD, FONT_NEAR)
mask_far  = render_mask(FAR_WORD, FONT_FAR)

dist_near = distance_transform_edt(mask_near)
dist_near /= dist_near.max()
edge_dist = 1 - dist_near

dist_far = distance_transform_edt(mask_far)
dist_far /= dist_far.max()

# ================= INITIAL PRESET =================
EDGE_POWER  = 6.0
EDGE_INK    = 0.45
NEAR_SCALE  = 0.75

SPINE_POWER = 2.2
SPINE_INK   = 0.45

FAR_BLUR    = 10.0   # <<< VERY DIFFUSE FAR
VIEW_BLUR   = 6.0

# ================= FIGURE =================
fig, (ax_main, ax_far) = plt.subplots(2, 1, figsize=(10, 6))
plt.subplots_adjust(left=0.15, bottom=0.35)

img_main = ax_main.imshow(np.ones((H, W)), cmap="gray", vmin=0, vmax=1)
ax_main.set_title("Near View (read MONTH)")
ax_main.axis("off")

img_far = ax_far.imshow(np.ones((H, W)), cmap="gray", vmin=0, vmax=1)
ax_far.set_title("Far View (read MARCH)")
ax_far.axis("off")

# ================= UPDATE =================
def update(val=None):
    # NEAR: crisp edge detail
    near_val = 1 - EDGE_INK * (edge_dist ** EDGE_POWER)

    # FAR: diffuse mass only
    far_val = 1 - SPINE_INK * (dist_far ** SPINE_POWER)
    far_val = gaussian_filter(far_val, sigma=FAR_BLUR)
    far_val = 1 - 0.5 * (1 - far_val)  # contrast compression

    out = np.ones((H, W))
    out[mask_far]  -= (1 - far_val[mask_far])
    out[mask_near] -= NEAR_SCALE * (1 - near_val[mask_near])
    out = np.clip(out, 0, 1)

    img_main.set_data(out)
    img_far.set_data(gaussian_filter(out, sigma=VIEW_BLUR))
    fig.canvas.draw_idle()

# ================= SLIDERS =================
axes = {
    "Near Edge Power": (4.0, 8.0, EDGE_POWER),
    "Near Scale":      (0.4, 0.9, NEAR_SCALE),
    "Far Blur":        (6.0, 16.0, FAR_BLUR),
    "Far Ink":         (0.3, 0.6, SPINE_INK),
    "View Blur":       (4.0, 10.0, VIEW_BLUR),
}

sliders = {}
y = 0.28
for name, (a, b, v) in axes.items():
    ax = plt.axes([0.15, y, 0.7, 0.02])
    sliders[name] = Slider(ax, name, a, b, valinit=v)
    y -= 0.035

def on_change(val):
    global EDGE_POWER, NEAR_SCALE, FAR_BLUR, SPINE_INK, VIEW_BLUR
    EDGE_POWER = sliders["Near Edge Power"].val
    NEAR_SCALE = sliders["Near Scale"].val
    FAR_BLUR   = sliders["Far Blur"].val
    SPINE_INK  = sliders["Far Ink"].val
    VIEW_BLUR  = sliders["View Blur"].val
    update()

for s in sliders.values():
    s.on_changed(on_change)

# ================= DRAW =================
update()
plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt, gaussian_filter
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider

# ---------- CANVAS ----------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "MONTH"
FAR_WORD  = "MARCH"

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# ---------- RENDER MASK ----------
def render_mask(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0, 0), word, font=f)
    x = (W - (bbox[2] - bbox[0])) // 2
    y = (H - (bbox[3] - bbox[1])) // 2
    d.text((x, y), word, 0, font=f)
    return (np.array(img) < 128)

# ---------- MASKS ----------
mask_near = render_mask(NEAR_WORD, FONT_NEAR)
mask_far  = render_mask(FAR_WORD, FONT_FAR)

# ---------- DISTANCE FIELDS ----------
dist_near = distance_transform_edt(mask_near)
dist_near /= dist_near.max()
edge_dist = 1 - dist_near

dist_far = distance_transform_edt(mask_far)
dist_far /= dist_far.max()

# ---------- INITIAL VALUES (KNOWN GOOD) ----------
EDGE_POWER  = 5.8
EDGE_INK    = 0.45
NEAR_SCALE  = 0.70

SPINE_POWER = 2.5
SPINE_INK   = 0.45

FAR_BLUR    = 4.5   # <<< IMPORTANT FIX
VIEW_BLUR   = 6.0

# ---------- FIGURE ----------
fig, (ax_main, ax_far) = plt.subplots(2, 1, figsize=(10, 6))
plt.subplots_adjust(left=0.15, bottom=0.38)

img_main = ax_main.imshow(np.ones((H, W)), cmap="gray", vmin=0, vmax=1)
ax_main.set_title("Composite (Near View)")
ax_main.axis("off")

img_far = ax_far.imshow(np.ones((H, W)), cmap="gray", vmin=0, vmax=1)
ax_far.set_title("Simulated Far View")
ax_far.axis("off")

# ---------- UPDATE ----------
def update(val=None):
    near_val = 1 - EDGE_INK * (edge_dist ** EDGE_POWER)

    far_val = 1 - SPINE_INK * (dist_far ** SPINE_POWER)
    far_val = gaussian_filter(far_val, sigma=FAR_BLUR)  # <<< STRONG SOURCE BLUR

    out = np.ones((H, W))
    out[mask_far]  -= (1 - far_val[mask_far])
    out[mask_near] -= NEAR_SCALE * (1 - near_val[mask_near])
    out = np.clip(out, 0, 1)

    img_main.set_data(out)
    img_far.set_data(gaussian_filter(out, sigma=VIEW_BLUR))
    fig.canvas.draw_idle()

# ---------- SLIDERS ----------
ax_fb = plt.axes([0.15, 0.32, 0.7, 0.02])
ax_ns = plt.axes([0.15, 0.29, 0.7, 0.02])
ax_ep = plt.axes([0.15, 0.26, 0.7, 0.02])
ax_sp = plt.axes([0.15, 0.23, 0.7, 0.02])
ax_vb = plt.axes([0.15, 0.20, 0.7, 0.02])

s_fb = Slider(ax_fb, "Far Source Blur", 2.0, 8.0, valinit=FAR_BLUR)
s_ns = Slider(ax_ns, "Near Scale",      0.4, 0.8, valinit=NEAR_SCALE)
s_ep = Slider(ax_ep, "Near Edge Power", 4.0, 7.0, valinit=EDGE_POWER)
s_sp = Slider(ax_sp, "Far Spine Power", 1.8, 3.5, valinit=SPINE_POWER)
s_vb = Slider(ax_vb, "View Blur",        4.0, 10.0, valinit=VIEW_BLUR)

def on_change(val):
    global FAR_BLUR, NEAR_SCALE, EDGE_POWER, SPINE_POWER, VIEW_BLUR
    FAR_BLUR    = s_fb.val
    NEAR_SCALE  = s_ns.val
    EDGE_POWER  = s_ep.val
    SPINE_POWER = s_sp.val
    VIEW_BLUR   = s_vb.val
    update()

for s in [s_fb, s_ns, s_ep, s_sp, s_vb]:
    s.on_changed(on_change)

# ---------- DRAW ----------
update()
plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt, gaussian_filter
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider

# ---------- CANVAS ----------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "MONTH"
FAR_WORD  = "MARCH"

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# ---------- RENDER MASK ----------
def render_mask(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0, 0), word, font=f)
    x = (W - (bbox[2] - bbox[0])) // 2
    y = (H - (bbox[3] - bbox[1])) // 2
    d.text((x, y), word, 0, font=f)
    return (np.array(img) < 128)

# ---------- MASKS ----------
mask_near = render_mask(NEAR_WORD, FONT_NEAR)
mask_far  = render_mask(FAR_WORD, FONT_FAR)

# ---------- DISTANCE FIELDS ----------
dist_near = distance_transform_edt(mask_near)
dist_near /= dist_near.max()
edge_dist = 1 - dist_near

dist_far = distance_transform_edt(mask_far)
dist_far /= dist_far.max()

# ---------- KNOWN-GOOD INITIAL VALUES ----------
EDGE_POWER  = 5.8
EDGE_INK    = 0.45
NEAR_SCALE  = 0.70

SPINE_POWER = 2.5
SPINE_INK   = 0.45

FAR_BLUR    = 2.0
VIEW_BLUR   = 6.0

# ---------- FIGURE ----------
fig, (ax_main, ax_far) = plt.subplots(2, 1, figsize=(10, 6))
plt.subplots_adjust(left=0.15, bottom=0.38)

img_main = ax_main.imshow(np.ones((H, W)), cmap="gray", vmin=0, vmax=1)
ax_main.set_title("Composite (Near View)")
ax_main.axis("off")

img_far = ax_far.imshow(np.ones((H, W)), cmap="gray", vmin=0, vmax=1)
ax_far.set_title("Simulated Far View")
ax_far.axis("off")

# ---------- UPDATE ----------
def update(val=None):
    near_val = 1 - EDGE_INK * (edge_dist ** EDGE_POWER)

    far_val = 1 - SPINE_INK * (dist_far ** SPINE_POWER)
    far_val = gaussian_filter(far_val, sigma=FAR_BLUR)  # <<< CRITICAL FIX

    out = np.ones((H, W))
    out[mask_far]  -= (1 - far_val[mask_far])
    out[mask_near] -= NEAR_SCALE * (1 - near_val[mask_near])
    out = np.clip(out, 0, 1)

    img_main.set_data(out)
    img_far.set_data(gaussian_filter(out, sigma=VIEW_BLUR))
    fig.canvas.draw_idle()

# ---------- SLIDERS ----------
ax_ep = plt.axes([0.15, 0.32, 0.7, 0.02])
ax_ei = plt.axes([0.15, 0.29, 0.7, 0.02])
ax_ns = plt.axes([0.15, 0.26, 0.7, 0.02])
ax_sp = plt.axes([0.15, 0.23, 0.7, 0.02])
ax_si = plt.axes([0.15, 0.20, 0.7, 0.02])
ax_fb = plt.axes([0.15, 0.17, 0.7, 0.02])
ax_vb = plt.axes([0.15, 0.14, 0.7, 0.02])

s_ep = Slider(ax_ep, "Near Edge Power", 4.0, 7.0, valinit=EDGE_POWER)
s_ei = Slider(ax_ei, "Near Ink",        0.3, 0.6, valinit=EDGE_INK)
s_ns = Slider(ax_ns, "Near Scale",      0.4, 0.8, valinit=NEAR_SCALE)
s_sp = Slider(ax_sp, "Far Spine Power",  1.8, 3.5, valinit=SPINE_POWER)
s_si = Slider(ax_si, "Far Ink",          0.3, 0.6, valinit=SPINE_INK)
s_fb = Slider(ax_fb, "Far Blur",         1.0, 4.0, valinit=FAR_BLUR)
s_vb = Slider(ax_vb, "View Blur",        4.0, 10.0, valinit=VIEW_BLUR)

def on_change(val):
    global EDGE_POWER, EDGE_INK, NEAR_SCALE, SPINE_POWER, SPINE_INK, FAR_BLUR, VIEW_BLUR
    EDGE_POWER  = s_ep.val
    EDGE_INK    = s_ei.val
    NEAR_SCALE  = s_ns.val
    SPINE_POWER = s_sp.val
    SPINE_INK   = s_si.val
    FAR_BLUR    = s_fb.val
    VIEW_BLUR   = s_vb.val
    update()

for s in [s_ep, s_ei, s_ns, s_sp, s_si, s_fb, s_vb]:
    s.on_changed(on_change)

# ---------- DRAW ----------
update()
plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt, gaussian_filter
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider

# ---------- CANVAS ----------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "MONTH"
FAR_WORD  = "MARCH"

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# ---------- RENDER MASK ----------
def render_mask(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0, 0), word, font=f)
    x = (W - (bbox[2] - bbox[0])) // 2
    y = (H - (bbox[3] - bbox[1])) // 2
    d.text((x, y), word, 0, font=f)
    return (np.array(img) < 128)

# ---------- MASKS + DISTANCE FIELDS ----------
mask_near = render_mask(NEAR_WORD, FONT_NEAR)
mask_far  = render_mask(FAR_WORD, FONT_FAR)

dist_near = distance_transform_edt(mask_near)
dist_near /= dist_near.max()
edge_dist = 1 - dist_near

dist_far = distance_transform_edt(mask_far)
dist_far /= dist_far.max()

# ---------- INITIAL (KNOWN-GOOD) PARAMETERS ----------
EDGE_POWER  = 5.5
EDGE_INK    = 0.45
NEAR_SCALE  = 0.65

SPINE_POWER = 2.8
SPINE_INK   = 0.45

BLUR_SIGMA  = 6

# ---------- FIGURE ----------
fig, (ax_main, ax_blur) = plt.subplots(2, 1, figsize=(10, 6))
plt.subplots_adjust(left=0.15, bottom=0.35)

img_main = ax_main.imshow(np.ones((H, W)), cmap="gray", vmin=0, vmax=1)
ax_main.set_title("Composite (Near View)")
ax_main.axis("off")

img_blur = ax_blur.imshow(np.ones((H, W)), cmap="gray", vmin=0, vmax=1)
ax_blur.set_title("Simulated Far View")
ax_blur.axis("off")

# ---------- UPDATE FUNCTION ----------
def update(val=None):
    near_val = 1 - EDGE_INK * (edge_dist ** EDGE_POWER)
    far_val  = 1 - SPINE_INK * (dist_far ** SPINE_POWER)

    out = np.ones((H, W))
    out[mask_far]  -= (1 - far_val[mask_far])
    out[mask_near] -= NEAR_SCALE * (1 - near_val[mask_near])
    out = np.clip(out, 0, 1)

    img_main.set_data(out)
    img_blur.set_data(gaussian_filter(out, sigma=BLUR_SIGMA))
    fig.canvas.draw_idle()

# ---------- SLIDERS ----------
ax_ep = plt.axes([0.15, 0.28, 0.7, 0.02])
ax_ei = plt.axes([0.15, 0.25, 0.7, 0.02])
ax_ns = plt.axes([0.15, 0.22, 0.7, 0.02])
ax_sp = plt.axes([0.15, 0.19, 0.7, 0.02])
ax_si = plt.axes([0.15, 0.16, 0.7, 0.02])
ax_bs = plt.axes([0.15, 0.13, 0.7, 0.02])

s_ep = Slider(ax_ep, "Near Edge Power", 3.0, 7.0, valinit=EDGE_POWER)
s_ei = Slider(ax_ei, "Near Ink",        0.2, 0.6, valinit=EDGE_INK)
s_ns = Slider(ax_ns, "Near Scale",      0.3, 0.8, valinit=NEAR_SCALE)
s_sp = Slider(ax_sp, "Far Spine Power",  1.5, 4.0, valinit=SPINE_POWER)
s_si = Slider(ax_si, "Far Ink",          0.3, 0.7, valinit=SPINE_INK)
s_bs = Slider(ax_bs, "Blur Sigma",       3.0, 10.0, valinit=BLUR_SIGMA)

def on_change(val):
    global EDGE_POWER, EDGE_INK, NEAR_SCALE, SPINE_POWER, SPINE_INK, BLUR_SIGMA
    EDGE_POWER  = s_ep.val
    EDGE_INK    = s_ei.val
    NEAR_SCALE  = s_ns.val
    SPINE_POWER = s_sp.val
    SPINE_INK   = s_si.val
    BLUR_SIGMA  = s_bs.val
    update()

for s in [s_ep, s_ei, s_ns, s_sp, s_si, s_bs]:
    s.on_changed(on_change)

# ---------- INITIAL DRAW ----------
update()
plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt, gaussian_filter
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider

# ---------- CANVAS ----------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "MONTH"
FAR_WORD  = "MARCH"

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# ---------- RENDER MASK ----------
def render_mask(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0, 0), word, font=f)
    x = (W - (bbox[2] - bbox[0])) // 2
    y = (H - (bbox[3] - bbox[1])) // 2
    d.text((x, y), word, 0, font=f)
    return (np.array(img) < 128)

# ---------- MASKS + DISTANCES (ONCE) ----------
mask_near = render_mask(NEAR_WORD, FONT_NEAR)
mask_far  = render_mask(FAR_WORD, FONT_FAR)

dist_near = distance_transform_edt(mask_near)
dist_near /= dist_near.max()
edge_dist = 1 - dist_near

dist_far = distance_transform_edt(mask_far)
dist_far /= dist_far.max()

# ---------- INITIAL PARAMETERS ----------
EDGE_POWER  = 4.5
EDGE_INK    = 0.45
SPINE_POWER = 2.0
SPINE_INK   = 0.55
NEAR_SCALE  = 0.4
BLUR_SIGMA  = 6

# ---------- FIGURE ----------
fig, (ax_main, ax_blur) = plt.subplots(2, 1, figsize=(10, 6))
plt.subplots_adjust(left=0.15, bottom=0.35)

img_main = ax_main.imshow(np.ones((H, W)), cmap="gray", vmin=0, vmax=1)
ax_main.set_title("Composite (Near View)")
ax_main.axis("off")

img_blur = ax_blur.imshow(np.ones((H, W)), cmap="gray", vmin=0, vmax=1)
ax_blur.set_title("Simulated Far View")
ax_blur.axis("off")

# ---------- UPDATE FUNCTION ----------
def update(val=None):
    near_val = 1 - EDGE_INK * (edge_dist ** EDGE_POWER)
    far_val  = 1 - SPINE_INK * (dist_far ** SPINE_POWER)

    out = np.ones((H, W))
    out[mask_far]  -= (1 - far_val[mask_far])
    out[mask_near] -= NEAR_SCALE * (1 - near_val[mask_near])
    out = np.clip(out, 0, 1)

    img_main.set_data(out)
    img_blur.set_data(gaussian_filter(out, sigma=BLUR_SIGMA))
    fig.canvas.draw_idle()

# ---------- SLIDERS ----------
ax_ep = plt.axes([0.15, 0.28, 0.7, 0.02])
ax_ei = plt.axes([0.15, 0.25, 0.7, 0.02])
ax_sp = plt.axes([0.15, 0.22, 0.7, 0.02])
ax_si = plt.axes([0.15, 0.19, 0.7, 0.02])
ax_ns = plt.axes([0.15, 0.16, 0.7, 0.02])

s_ep = Slider(ax_ep, "Near Edge Power", 2.0, 6.0, valinit=EDGE_POWER)
s_ei = Slider(ax_ei, "Near Ink",        0.2, 0.6, valinit=EDGE_INK)
s_sp = Slider(ax_sp, "Far Spine Power",  1.2, 4.0, valinit=SPINE_POWER)
s_si = Slider(ax_si, "Far Ink",          0.3, 0.8, valinit=SPINE_INK)
s_ns = Slider(ax_ns, "Near Scale",       0.2, 0.6, valinit=NEAR_SCALE)

def on_change(val):
    global EDGE_POWER, EDGE_INK, SPINE_POWER, SPINE_INK, NEAR_SCALE
    EDGE_POWER  = s_ep.val
    EDGE_INK    = s_ei.val
    SPINE_POWER = s_sp.val
    SPINE_INK   = s_si.val
    NEAR_SCALE  = s_ns.val
    update()

for s in [s_ep, s_ei, s_sp, s_si, s_ns]:
    s.on_changed(on_change)

# ---------- INITIAL DRAW ----------
update()
plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt, gaussian_filter
import matplotlib.pyplot as plt

# ---------- CANVAS ----------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "MONTH"
FAR_WORD  = "MARCH"

# ---------- NEAR (edge detail) ----------
EDGE_POWER = 3.5
EDGE_INK   = 0.45

# ---------- FAR (mass / spine) ----------
SPINE_POWER = 2.5
SPINE_INK   = 0.55

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# ---------- RENDER MASK ----------
def render_mask(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0, 0), word, font=f)
    x = (W - (bbox[2] - bbox[0])) // 2
    y = (H - (bbox[3] - bbox[1])) // 2
    d.text((x, y), word, 0, font=f)
    return (np.array(img) < 128)

# ---------- NEAR WORD ----------
mask_near = render_mask(NEAR_WORD, FONT_NEAR)
dist_near = distance_transform_edt(mask_near)
dist_near /= dist_near.max()
edge_dist = 1 - dist_near
near_val = 1 - EDGE_INK * (edge_dist ** EDGE_POWER)

# ---------- FAR WORD ----------
mask_far = render_mask(FAR_WORD, FONT_FAR)
dist_far = distance_transform_edt(mask_far)
dist_far /= dist_far.max()
far_val = 1 - SPINE_INK * (dist_far ** SPINE_POWER)

# ---------- COMPOSITE (CRITICAL PART) ----------
out = np.ones((H, W))

# FAR lays down mass
out[mask_far] -= (1 - far_val[mask_far])

# NEAR adds detail (weaker, non-destructive)
out[mask_near] -= 0.6 * (1 - near_val[mask_near])

out = np.clip(out, 0, 1)

# ---------- DISPLAY ----------
plt.figure(figsize=(10, 4))
plt.imshow(out, cmap="gray", vmin=0, vmax=1)
plt.axis("off")
plt.show()

# ---------- OPTIONAL: FAR VIEW SIMULATION ----------
blur = gaussian_filter(out, sigma=6)
plt.figure(figsize=(10, 4))
plt.imshow(blur, cmap="gray", vmin=0, vmax=1)
plt.title("Simulated FAR VIEW")
plt.axis("off")
plt.show()

saq w23esdzximport numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt
import matplotlib.pyplot as plt

# -------- SETTINGS --------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "MONTH"   # thin stroke
FAR_WORD  = "MARCH"   # thick stroke

# Near font (edge-dark)
EDGE_POWER = 3.0
EDGE_INK   = 0.5

# Far font (spine-dark)
SPINE_POWER = 3.5
SPINE_INK   = 0.35

FONT_NEAR = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_FAR  = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# -------- HELPER: RENDER MASK --------
def render_mask(word, font_path):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)

    bbox = d.textbbox((0, 0), word, font=f)
    x = (W - (bbox[2] - bbox[0])) // 2
    y = (H - (bbox[3] - bbox[1])) // 2
    d.text((x, y), word, 0, font=f)

    return (np.array(img) < 128)

# -------- NEAR WORD (MONTH, thin) --------
mask_near = render_mask(NEAR_WORD, FONT_NEAR)
dist_near = distance_transform_edt(mask_near)
dist_near /= dist_near.max()
edge_dist = 1 - dist_near

near_val = 1 - EDGE_INK * (edge_dist ** EDGE_POWER)

# -------- FAR WORD (MARCH, thick) --------
mask_far = render_mask(FAR_WORD, FONT_FAR)
dist_far = distance_transform_edt(mask_far)
dist_far /= dist_far.max()

far_val = 1 - SPINE_INK * (dist_far ** SPINE_POWER)

# -------- SUPERIMPOSE (WHITE BACKGROUND) --------
out = np.ones((H, W))

out[mask_far]  = np.minimum(out[mask_far], far_val[mask_far])
out[mask_near] = np.minimum(out[mask_near], near_val[mask_near])

# -------- DISPLAY --------
plt.figure(figsize=(10, 4))
plt.imshow(out, cmap="gray", vmin=0, vmax=1)
plt.axis("off")
plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt
import matplotlib.pyplot as plt

# -------- SETTINGS --------
W, H = 800, 300

NEAR_WORD = "MONTH"
FAR_WORD  = "MARCH"

# FONT SIZES (THIS IS THE KEY DIFFERENCE)
FONT_SIZE_NEAR = 200
FONT_SIZE_FAR  = 230   # <<< FATTER LETTERS

# Near font (dark edge)
EDGE_POWER = 3.0
EDGE_INK   = 0.5

# Far font (dark spine)
SPINE_POWER = 3.5
SPINE_INK   = 0.35

FONT_PATH = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# -------- HELPER: RENDER WORD MASK --------
def render_mask(word, font_size):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(FONT_PATH, font_size)

    bbox = d.textbbox((0, 0), word, font=f)
    x = (W - (bbox[2] - bbox[0])) // 2
    y = (H - (bbox[3] - bbox[1])) // 2
    d.text((x, y), word, 0, font=f)

    return (np.array(img) < 128)

# -------- NEAR WORD (MONTH) --------
mask_near = render_mask(NEAR_WORD, FONT_SIZE_NEAR)
dist_near = distance_transform_edt(mask_near)
dist_near /= dist_near.max()
edge_dist = 1 - dist_near

font_near = 1 - EDGE_INK * (edge_dist ** EDGE_POWER)
near_out = np.ones_like(font_near)
near_out[mask_near] = font_near[mask_near]

# -------- FAR WORD (MARCH) --------
mask_far = render_mask(FAR_WORD, FONT_SIZE_FAR)
dist_far = distance_transform_edt(mask_far)
dist_far /= dist_far.max()

font_far = 1 - SPINE_INK * (dist_far ** SPINE_POWER)
far_out = np.ones_like(font_far)
far_out[mask_far] = font_far[mask_far]

# -------- DISPLAY --------
plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.imshow(near_out, cmap="gray", vmin=0, vmax=1)
plt.title("NEAR — MONTH (thinner)")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(far_out, cmap="gray", vmin=0, vmax=1)
plt.title("FAR — MARCH (fatter)")
plt.axis("off")

plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt, binary_dilation
import matplotlib.pyplot as plt

# -------- SETTINGS --------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "MONTH"
FAR_WORD  = "MARCH"

# Near font (thin, edge-dark)
EDGE_POWER = 3.0
EDGE_INK   = 0.5

# Far font (thick stroke, spine-dark)
SPINE_POWER = 3.5
SPINE_INK   = 0.35
STROKE_GROW = 4   # <<< THIS IS THE BROADER-STROKE KNOB (3–8)

FONT_PATH = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# -------- HELPER: RENDER WORD MASK --------
def render_mask(word):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(FONT_PATH, FONT_SIZE)
    bbox = d.textbbox((0, 0), word, font=f)
    x = (W - (bbox[2] - bbox[0])) // 2
    y = (H - (bbox[3] - bbox[1])) // 2
    d.text((x, y), word, 0, font=f)
    return (np.array(img) < 128)

# -------- NEAR WORD (MONTH) --------
mask_near = render_mask(NEAR_WORD)
dist_near = distance_transform_edt(mask_near)
dist_near /= dist_near.max()
edge_dist = 1 - dist_near

font_near = 1 - EDGE_INK * (edge_dist ** EDGE_POWER)
near_out = np.ones_like(font_near)
near_out[mask_near] = font_near[mask_near]

# -------- FAR WORD (MARCH) --------
mask_far = render_mask(FAR_WORD)

# <<< BROADEN THE STROKE GEOMETRICALLY >>>
structure = np.ones((STROKE_GROW, STROKE_GROW))
mask_far_thick = binary_dilation(mask_far, structure=structure)

dist_far = distance_transform_edt(mask_far_thick)
dist_far /= dist_far.max()

font_far = 1 - SPINE_INK * (dist_far ** SPINE_POWER)
far_out = np.ones_like(font_far)
far_out[mask_far_thick] = font_far[mask_far_thick]

# -------- DISPLAY --------
plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.imshow(near_out, cmap="gray", vmin=0, vmax=1)
plt.title("NEAR — thin stroke (MONTH)")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(far_out, cmap="gray", vmin=0, vmax=1)
plt.title("FAR — BROADER stroke (MARCH)")
plt.axis("off")

plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt, binary_dilation
import matplotlib.pyplot as plt

# -------- SETTINGS --------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "MONTH"
FAR_WORD  = "MARCH"

# Near font (thin, edge-dark)
EDGE_POWER = 3.0
EDGE_INK   = 0.5

# Far font (thick, spine-dark)
SPINE_POWER = 3.5
SPINE_INK   = 0.35
FAR_THICKNESS = 3   # <<< key parameter (2–5 is typical)

FONT_PATH = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# -------- HELPER: RENDER WORD MASK --------
def render_mask(word):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(FONT_PATH, FONT_SIZE)
    bbox = d.textbbox((0, 0), word, font=f)
    x = (W - (bbox[2] - bbox[0])) // 2
    y = (H - (bbox[3] - bbox[1])) // 2
    d.text((x, y), word, 0, font=f)
    return (np.array(img) < 128)

# -------- NEAR WORD (MONTH) --------
mask_near = render_mask(NEAR_WORD)
dist_near = distance_transform_edt(mask_near)
dist_near /= dist_near.max()
edge_dist = 1 - dist_near

font_near = 1 - EDGE_INK * (edge_dist ** EDGE_POWER)
near_out = np.ones_like(font_near)
near_out[mask_near] = font_near[mask_near]

# -------- FAR WORD (MARCH) --------
mask_far = render_mask(FAR_WORD)

# <<< THICKEN FAR LETTERS >>>
mask_far_thick = binary_dilation(mask_far, iterations=FAR_THICKNESS)

dist_far = distance_transform_edt(mask_far_thick)
dist_far /= dist_far.max()

font_far = 1 - SPINE_INK * (dist_far ** SPINE_POWER)
far_out = np.ones_like(font_far)
far_out[mask_far_thick] = font_far[mask_far_thick]

# -------- DISPLAY --------
plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.imshow(near_out, cmap="gray", vmin=0, vmax=1)
plt.title("NEAR — MONTH (thin, dark edge)")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(far_out, cmap="gray", vmin=0, vmax=1)
plt.title("FAR — MARCH (thick, dark spine)")
plt.axis("off")

plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt
import matplotlib.pyplot as plt

# -------- SETTINGS --------
W, H = 800, 300
FONT_SIZE = 200

NEAR_WORD = "MONTH"
FAR_WORD  = "MARCH"

# Near font (dark edge)
EDGE_POWER = 3.0
EDGE_INK   = 0.5

# Far font (dark spine)
SPINE_POWER = 3.5
SPINE_INK   = 0.35

FONT_PATH = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# -------- HELPER: RENDER WORD MASK --------
def render_mask(word):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(FONT_PATH, FONT_SIZE)

    bbox = d.textbbox((0, 0), word, font=f)
    x = (W - (bbox[2] - bbox[0])) // 2
    y = (H - (bbox[3] - bbox[1])) // 2
    d.text((x, y), word, 0, font=f)

    return (np.array(img) < 128)

# -------- NEAR WORD (MONTH) --------
mask_near = render_mask(NEAR_WORD)
dist_near = distance_transform_edt(mask_near)
dist_near = dist_near / dist_near.max()
edge_dist = 1 - dist_near

font_near = 1 - EDGE_INK * (edge_dist ** EDGE_POWER)
near_out = np.ones_like(font_near)
near_out[mask_near] = font_near[mask_near]

# -------- FAR WORD (MARCH) --------
mask_far = render_mask(FAR_WORD)
dist_far = distance_transform_edt(mask_far)
dist_far = dist_far / dist_far.max()

font_far = 1 - SPINE_INK * (dist_far ** SPINE_POWER)
far_out = np.ones_like(font_far)
far_out[mask_far] = font_far[mask_far]

# -------- DISPLAY --------
plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.imshow(near_out, cmap="gray", vmin=0, vmax=1)
plt.title("NEAR — MONTH (dark edge)")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(far_out, cmap="gray", vmin=0, vmax=1)
plt.title("FAR — MARCH (dark spine)")
plt.axis("off")

plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt
import matplotlib.pyplot as plt

# -------- SETTINGS --------
W, H = 300, 500
FONT_SIZE = 300
LETTER = "I"

# Near font (dark edge)
EDGE_POWER = 3.0
EDGE_INK   = 0.5

# Far font (dark spine)
SPINE_POWER = 3.5
SPINE_INK   = 0.35

FONT_PATH = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# -------- RENDER LETTER ONCE --------
img = Image.new("L", (W, H), 255)
draw = ImageDraw.Draw(img)
font = ImageFont.truetype(FONT_PATH, FONT_SIZE)

bbox = draw.textbbox((0, 0), LETTER, font=font)
x = (W - (bbox[2] - bbox[0])) // 2
y = (H - (bbox[3] - bbox[1])) // 2
draw.text((x, y), LETTER, 0, font=font)

mask = (np.array(img) < 128)

# -------- DISTANCE FIELD (SHARED) --------
dist = distance_transform_edt(mask)
dist = dist / dist.max()   # 0 = edge, 1 = spine
edge_dist = 1 - dist       # 1 = edge, 0 = spine

# -------- NEAR FONT: DARK EDGE → LIGHT INSIDE --------
font_near = 1 - EDGE_INK * (edge_dist ** EDGE_POWER)

# -------- FAR FONT: DARK SPINE → LIGHT OUTWARD --------
font_far = 1 - SPINE_INK * (dist ** SPINE_POWER)

# -------- APPLY WHITE BACKGROUND --------
near_out = np.ones_like(font_near)
far_out  = np.ones_like(font_far)

near_out[mask] = font_near[mask]
far_out[mask]  = font_far[mask]

# -------- DISPLAY --------
plt.figure(figsize=(4, 8))

plt.subplot(1, 2, 1)
plt.imshow(near_out, cmap="gray", vmin=0, vmax=1)
plt.title("NEAR: dark edge")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(far_out, cmap="gray", vmin=0, vmax=1)
plt.title("FAR: dark spine")
plt.axis("off")

plt.show()

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt
import matplotlib.pyplot as plt

# -------- SETTINGS --------
W, H = 300, 500
FONT_SIZE = 300
LETTER = "I"

SPINE_POWER = 3.5     # higher = darker region hugs spine more
INK_STRENGTH = 0.35   # lower = keeps letter mostly white

FONT_PATH = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# -------- RENDER LETTER (ONCE) --------
img = Image.new("L", (W, H), 255)
d = ImageDraw.Draw(img)
f = ImageFont.truetype(FONT_PATH, FONT_SIZE)

bbox = d.textbbox((0, 0), LETTER, font=f)
x = (W - (bbox[2] - bbox[0])) // 2
y = (H - (bbox[3] - bbox[1])) // 2
d.text((x, y), LETTER, 0, font=f)

mask = (np.array(img) < 128)

# -------- DISTANCE FROM EDGE --------
dist = distance_transform_edt(mask)
dist = dist / dist.max()      # 0 = edge, 1 = spine

# -------- FAR FONT: DARK SPINE → LIGHT OUTWARD --------
font_far = 1 - INK_STRENGTH * (dist ** SPINE_POWER)

# -------- WHITE BACKGROUND --------
out = np.ones_like(font_far)
out[mask] = font_far[mask]

# -------- DISPLAY --------
plt.imshow(out, cmap="gray", vmin=0, vmax=1)
plt.axis("off")
plt.show()

!pip install pillow numpy scipy matplotlib -q

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt
import matplotlib.pyplot as plt

# -------- SETTINGS --------
W, H = 300, 500
FONT_SIZE = 300
LETTER = "I"

EDGE_POWER = 3.0     # higher = thinner dark border
INK_STRENGTH = 0.5   # lower = more white overall

FONT_PATH = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# -------- RENDER LETTER (ONCE) --------
img = Image.new("L", (W, H), 255)
d = ImageDraw.Draw(img)
f = ImageFont.truetype(FONT_PATH, FONT_SIZE)

bbox = d.textbbox((0, 0), LETTER, font=f)
x = (W - (bbox[2] - bbox[0])) // 2
y = (H - (bbox[3] - bbox[1])) // 2
d.text((x, y), LETTER, 0, font=f)

mask = (np.array(img) < 128)

# -------- DISTANCE FROM EDGE --------
dist = distance_transform_edt(mask)
dist = dist / dist.max()      # 0 = edge, 1 = center
edge_dist = 1 - dist          # 1 = edge, 0 = center

# -------- NEAR FONT: DARK EDGE → LIGHT INSIDE --------
font_near = 1 - INK_STRENGTH * (edge_dist ** EDGE_POWER)

# -------- WHITE BACKGROUND --------
out = np.ones_like(font_near)
out[mask] = font_near[mask]

# -------- DISPLAY --------
plt.imshow(out, cmap="gray", vmin=0, vmax=1)
plt.axis("off")
plt.show()

!pip install pillow numpy scipy matplotlib

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt
import matplotlib.pyplot as plt

# --- Settings ---
W, H = 300, 500
FONT_SIZE = 300
LETTER = "I"
GAMMA = 8

FONT_PATH = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

# --- Render EXACT letter shape once ---
img = Image.new("L", (W, H), 255)
d = ImageDraw.Draw(img)
f = ImageFont.truetype(FONT_PATH, FONT_SIZE)

bbox = d.textbbox((0, 0), LETTER, font=f)
x = (W - (bbox[2] - bbox[0])) // 2
y = (H - (bbox[3] - bbox[1])) // 2
d.text((x, y), LETTER, 0, font=f)

mask = (np.array(img) < 128)

# --- Distance field (shared) ---
dist = distance_transform_edt(mask)
dist = dist / dist.max()

EDGE_POWER_A = 2.5   # edge darkness (MONTH-style)
EDGE_POWER_B = 3.5   # spine darkness (MARCH-style)
DARK_SCALE_B = 0.35  # overall faintness of dark center

font_A = 1 - dist**EDGE_POWER_B
font_B = 1 - DARK_SCALE_B * (1 - dist**EDGE_POWER_B)

font_A_bg = np.ones_like(font_A)
font_B_bg = np.ones_like(font_B)

font_A_bg[mask] = font_A[mask]
font_B_bg[mask] = font_B[mask]

# --- Show side by side ---
plt.figure(figsize=(4, 8))

plt.subplot(1, 2, 1)
plt.imshow(font_A_bg, cmap="gray", vmin=0, vmax=1)
plt.title("Light center / Dark edge")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(font_B_bg, cmap="gray", vmin=0, vmax=1)
plt.title("Dark center / Light edge")
plt.axis("off")

plt.show()
# plt.figure(figsize=(4, 8))
# plt.subplot(1, 2, 1)
# plt.imshow(font_A, cmap="gray")
# plt.title("Light center / Dark edge")
# plt.axis("off")

# plt.subplot(1, 2, 2)
# plt.imshow(font_B, cmap="gray")
# plt.title("Dark center / Light edge")
# plt.axis("off")

# plt.show()

!pip install pillow numpy scipy matplotlib

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt
import matplotlib.pyplot as plt
import subprocess

# --- Settings ---
W, H = 300, 500
FONT_SIZE = 300
LETTER = "I"
GAMMA = 0.6   # edge darkness control (0.5–0.8 sweet spot)

# --- Find font ---
font_path = subprocess.check_output(
    ["bash", "-lc", "find /usr/share/fonts -name '*.ttf' | head -1"]
).decode().strip()

# --- Render letter mask ---
img = Image.new("L", (W, H), 255)
d = ImageDraw.Draw(img)
f = ImageFont.truetype(font_path, FONT_SIZE)
bbox = d.textbbox((0, 0), LETTER, font=f)
x = (W - (bbox[2]-bbox[0])) // 2
y = (H - (bbox[3]-bbox[1])) // 2
d.text((x, y), LETTER, 0, font=f)

mask = (np.array(img) < 128)
mask = mask.astype(bool)

# --- Distance from edge ---
dist = distance_transform_edt(mask)
dist = dist / dist.max()

# --- Map: light spine → dark edge ---
out = 2 - dist**GAMMA

plt.imshow(out, cmap="gray")
plt.axis("off")
plt.show()

!pip install pillow numpy scipy matplotlib

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt
import matplotlib.pyplot as plt
import subprocess

# --- Settings ---
W, H = 500, 500
FONT_SIZE = 260
LETTER = "O"

# --- Find font ---
font_path = subprocess.check_output(
    ["bash", "-lc", "find /usr/share/fonts -name '*.ttf' | head -1"]
).decode().strip()

# --- Render letter mask ---
img = Image.new("L", (W, H), 255)
d = ImageDraw.Draw(img)
f = ImageFont.truetype(font_path, FONT_SIZE)
bbox = d.textbbox((0, 0), LETTER, font=f)
x = (W - (bbox[2]-bbox[0])) // 2
y = (H - (bbox[3]-bbox[1])) // 2
d.text((x, y), LETTER, 0, font=f)

mask = (np.array(img) < 128).astype(int)

# --- Distance from edge (inside only) ---
dist = distance_transform_edt(mask)

# --- Normalize ---
dist = dist / dist.max()

# --- Map: center light, edge dark ---
out = 1 - dist

plt.imshow(out, cmap="gray")
plt.axis("off")
plt.show()

!pip install pillow numpy scipy matplotlib

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt
import subprocess

# --- Settings (LOCKED) ---
W, H = 500, 500
FONT_SIZE = 260
LETTER = "O"

# --- Find a font ---
font_path = subprocess.check_output(
    ["bash", "-lc", "find /usr/share/fonts -name '*.ttf' | head -1"]
).decode().strip()

print("Font:", font_path)

# --- Render binary letter ---
img = Image.new("L", (W, H), 255)
d = ImageDraw.Draw(img)
f = ImageFont.truetype(font_path, FONT_SIZE)
bbox = d.textbbox((0, 0), LETTER, font=f)
x = (W - (bbox[2]-bbox[0])) // 2
y = (H - (bbox[3]-bbox[1])) // 2
d.text((x, y), LETTER, 0, font=f)

letter = (np.array(img) < 128).astype(float)

# --- Frequency layers (CLEAN) ---
near = gaussian_filter(letter, sigma=1.2)   # preserves shape
far  = gaussian_filter(letter, sigma=10)    # soft mass, no spill

# --- Combine (stable weights) ---
out = 0.8 * near + 0.2 * far
out = 1 - out  # black letter on white

# --- Display ---
plt.imshow(out, cmap="gray")
plt.axis("off")
plt.show()

!pip install pillow numpy scipy matplotlib

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt
import subprocess

# --- Settings ---
W, H = 600, 300
FONT_SIZE = 200
NEAR = "O"     # start with ONE letter
FAR  = "O"

# --- Find any font ---
font_path = subprocess.check_output(
    ["bash", "-lc", "find /usr/share/fonts -name '*.ttf' | head -1"]
).decode().strip()

print("Font:", font_path)

# --- Render text (binary) ---
def render(word):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0, 0), word, font=f)
    x = (W - (bbox[2]-bbox[0])) // 2
    y = (H - (bbox[3]-bbox[1])) // 2
    d.text((x, y), word, 0, font=f)
    return (np.array(img) < 128).astype(float)

near = render(NEAR)
far  = render(FAR)

# --- Clean frequency split ---
near_clean = gaussian_filter(near, sigma=1)     # keep shape clean
far_clean  = gaussian_filter(far, sigma=25)    # big mass only

# --- Combine (simple weighted sum) ---
img = 0.6 * near_clean + 0.4 * far_clean
img = 1 - img  # black text on white

# --- Show ---
plt.imshow(img, cmap="gray")
plt.axis("off")
plt.show()

!pip install pillow numpy scipy matplotlib

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt
import subprocess

# --- Settings ---
W, H = 800, 300
FONT_SIZE = 180
NEAR = "MONTH"
FAR  = "MARCH"

# --- Find any TTF font automatically ---
font_path = subprocess.check_output(
    ["bash", "-lc", "find /usr/share/fonts -name '*.ttf' | head -1"]
).decode().strip()

print("Using font:", font_path)

# --- Render text ---
def render(word):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(font_path, FONT_SIZE)
    bbox = d.textbbox((0, 0), word, font=f)
    x = (W - (bbox[2]-bbox[0])) // 2
    y = (H - (bbox[3]-bbox[1])) // 2
    d.text((x, y), word, 0, font=f)
    return np.array(img) / 255.0

near = render(NEAR)
far  = render(FAR)

# --- Frequency separation ---
low  = gaussian_filter(far, sigma=18)
high = near - gaussian_filter(near, sigma=3)

# --- Combine ---
img = low + high
img = (img - img.min()) / (img.max() - img.min())

# --- Show ---
plt.imshow(img, cmap="gray")
plt.axis("off")
plt.show()

# Install deps (usually already installed)
!pip install pillow numpy scipy matplotlib

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt
import os

# --- Settings ---
W, H = 800, 300
FONT_SIZE = 180
NEAR = "MONTH"
FAR  = "MARCH"

# --- Find a working font ---
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
assert os.path.exists(FONT), "Font not found"

# --- Render text ---
def render(word):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(FONT, FONT_SIZE)
    bbox = d.textbbox((0, 0), word, font=f)
    x = (W - (bbox[2]-bbox[0])) // 2
    y = (H - (bbox[3]-bbox[1])) // 2
    d.text((x, y), word, 0, font=f)
    return np.array(img) / 255.0

near = render(NEAR)
far  = render(FAR)

# --- Frequency separation ---
low  = gaussian_filter(far, sigma=18)
high = near - gaussian_filter(near, sigma=3)

# --- Combine ---
img = low + high
img = (img - img.min()) / (img.max() - img.min())

# --- Show ---
plt.imshow(img, cmap="gray")
plt.axis("off")
plt.show()

# Install deps (Colab usually has these, but safe)
!pip install pillow numpy scipy matplotlib

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt

# --- Settings (tweak only these) ---
W, H = 800, 300
FONT_SIZE = 180
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"  # works in Colab
NEAR = "MONTH"   # seen close
FAR  = "MARCH"   # seen far

# --- Render text ---
def render(word):
    img = Image.new("L", (W, H), 255)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(FONT, FONT_SIZE)
    bbox = d.textbbox((0, 0), word, font=f)
    x = (W - (bbox[2]-bbox[0])) // 2
    y = (H - (bbox[3]-bbox[1])) // 2
    d.text((x, y), word, 0, font=f)
    return np.array(img) / 255.0

near = render(NEAR)
far  = render(FAR)

# --- Frequency separation ---
low  = gaussian_filter(far, sigma=18)           # low-frequency (distance)
high = near - gaussian_filter(near, sigma=3)   # high-frequency (close)

# --- Combine ---
img = low + high
img = (img - img.min()) / (img.max() - img.min())

# --- Show ---
plt.imshow(img, cmap="gray")
plt.axis("off")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image, ImageFilter
from IPython.display import display

WORD = "MONTH"

# ---------- BUBBLE / HOLLOW LETTERS ----------
fig, ax = plt.subplots(figsize=(10,3))
ax.text(
    0.5, 0.5, WORD,
    fontsize=120,
    ha='center', va='center',
    color='white',
    path_effects=[],
)
ax.text(
    0.5, 0.5, WORD,
    fontsize=120,
    ha='center', va='center',
    color='none',
    stroke=4
)
ax.set_facecolor('black')
ax.axis('off')

fig.canvas.draw()
bubble = np.frombuffer(fig.canvas.tostring_rgb(), dtype=np.uint8)
bubble = bubble.reshape(fig.canvas.get_width_height()[::-1] + (3,))
plt.close(fig)

display(Image.fromarray(bubble))

# ---------- CLOUDY LETTERS ----------
fig, ax = plt.subplots(figsize=(10,3))
ax.text(
    0.5, 0.5, WORD,
    fontsize=120,
    ha='center', va='center',
    color='gray'
)
ax.set_facecolor('black')
ax.axis('off')

fig.canvas.draw()
cloud = np.frombuffer(fig.canvas.tostring_rgb(), dtype=np.uint8)
cloud = cloud.reshape(fig.canvas.get_width_height()[::-1] + (3,))
plt.close(fig)

cloud_img = Image.fromarray(cloud).filter(ImageFilter.GaussianBlur(8))
display(cloud_img)

from google.colab import drive
drive.mount('/content/drive')

"""After running the cell above and following the authentication steps, your Google Drive will be mounted at `/content/drive`. You can then access your files using paths like `/content/drive/My Drive/your_folder/your_file.csv`."""

# ---------- REAL MVP (ONE CELL) ----------
!wget -q https://github.com/google/fonts/raw/main/ofl/montserrat/Montserrat-Bold.ttf

from PIL import Image, ImageDraw, ImageFont, ImageFilter
import numpy as np
from IPython.display import display

# ---- CONFIG ----
NEAR_WORD = "Month"
FAR_WORD  = "March"

W, H = 1400, 400
FONT_SIZE = 280
FONT = ImageFont.truetype("Montserrat-Bold.ttf", FONT_SIZE)

# ---- NEAR (SHARP / BUBBLE BASE) ----
near = Image.new("L", (W, H), 0)
dn = ImageDraw.Draw(near)
dn.text((100, 50), NEAR_WORD, fill=240, font=FONT, stroke_width=10, stroke_fill=40)

# ---- FAR (CLOUD WORD) ----
far = Image.new("L", (W, H), 0)
df = ImageDraw.Draw(far)
df.text((100, 50), FAR_WORD, fill=160, font=FONT)
far = far.filter(ImageFilter.GaussianBlur(30))

# ---- COMBINE ----
combined = np.clip(
    np.array(near) + np.array(far),
    0, 255
)

final = Image.fromarray(combined.astype("uint8"))
display(final)

from PIL import Image, ImageDraw, ImageFilter, ImageFont
import numpy as np
from IPython.display import display

# -------- CONFIG --------
NEAR_WORD = "MONTH"
FAR_WORD  = "MARCH"

SCALE = 10        # hack: scale small text up
W, H = 120, 30    # small canvas (will scale)

# -------- SMALL IMAGES --------
near_small = Image.new("L", (W, H), 0)
far_small  = Image.new("L", (W, H), 0)

draw_near = ImageDraw.Draw(near_small)
draw_far  = ImageDraw.Draw(far_small)

font = ImageFont.load_default()

draw_near.text((5, 5), NEAR_WORD, fill=255, font=font)
draw_far.text((5, 5), FAR_WORD, fill=180, font=font)

# -------- BLUR FAR WORD --------
far_small = far_small.filter(ImageFilter.GaussianBlur(2))

# -------- SCALE UP --------
near = near_small.resize((W*SCALE, H*SCALE), Image.NEAREST)
far  = far_small.resize((W*SCALE, H*SCALE), Image.BILINEAR)

# -------- COMBINE --------
combined = np.clip(
    np.array(near) + np.array(far),
    0, 255
)

final = Image.fromarray(combined.astype("uint8"))

display(final)

from PIL import Image, ImageDraw, ImageFilter, ImageFont
import numpy as np
from IPython.display import display

# -------- CONFIG --------
NEAR_WORD = "MONTH"
FAR_WORD  = "MARCH"

W, H = 1200, 300

# -------- CREATE IMAGES --------
near = Image.new("L", (W, H), 0)
far  = Image.new("L", (W, H), 0)

draw_near = ImageDraw.Draw(near)
draw_far  = ImageDraw.Draw(far)

# -------- BUILT-IN FONT (ALWAYS EXISTS) --------
font = ImageFont.load_default()

# -------- DRAW TEXT --------
draw_near.text((200, 120), NEAR_WORD, fill=255, font=font)
draw_far.text((200, 120), FAR_WORD, fill=180, font=font)

# -------- BLUR FAR WORD --------
far = far.filter(ImageFilter.GaussianBlur(12))

# -------- COMBINE --------
combined = np.clip(
    np.array(near) + np.array(far),
    0, 255
)

final = Image.fromarray(combined.astype("uint8"))

# -------- DISPLAY (COLAB SAFE) --------
display(final)

from PIL import Image, ImageDraw, ImageFilter, ImageFont
import numpy as np

# -------- CONFIG --------
NEAR_WORD = "MONTH"
FAR_WORD  = "MARCH"

W, H = 1200, 300

# -------- CREATE IMAGES --------
near = Image.new("L", (W, H), 0)
far  = Image.new("L", (W, H), 0)

draw_near = ImageDraw.Draw(near)
draw_far  = ImageDraw.Draw(far)

# -------- BUILT-IN FONT (ALWAYS EXISTS) --------
font = ImageFont.load_default()

# -------- DRAW TEXT --------
draw_near.text((200, 120), NEAR_WORD, fill=255, font=font)
draw_far.text((200, 120), FAR_WORD, fill=180, font=font)

# -------- BLUR FAR WORD --------
far = far.filter(ImageFilter.GaussianBlur(12))

# -------- COMBINE --------
combined = np.clip(
    np.array(near) + np.array(far),
    0, 255
)

final = Image.fromarray(combined.astype("uint8"))
final.show()

from PIL import Image, ImageDraw, ImageFilter
import numpy as np

# -------- CONFIG --------
NEAR_WORD = "MONTH"
FAR_WORD  = "MARCH"

W, H = 1200, 300

# -------- CREATE CANVAS --------
img_near = Image.new("L", (W, H), 0)
img_far  = Image.new("L", (W, H), 0)

draw_near = ImageDraw.Draw(img_near)
draw_far  = ImageDraw.Draw(img_far)

# -------- USE BUILT-IN FONT (ALWAYS EXISTS) --------
font = ImageDraw.ImageFont.load_default()

# -------- DRAW TEXT --------
draw_near.text((200, 120), NEAR_WORD, fill=255)
draw_far.text((200, 120), FAR_WORD, fill=180)

# -------- BLUR FAR WORD --------
img_far = img_far.filter(ImageFilter.GaussianBlur(15))

# -------- COMBINE --------
combined = np.clip(
    np.array(img_near) + np.array(img_far),
    0, 255
)

final = Image.fromarray(combined.astype("uint8"))
final.show()

# --------- ONE CELL MVP (COLAB SAFE) ---------
from PIL import Image, ImageDraw, ImageFont, ImageFilter
import numpy as np

# --------- CONFIG ----------
NEAR_WORD = "Month"
FAR_WORD  = "March"

W, H = 1200, 350
FONT_SIZE = 260

# --------- LOAD DEFAULT FONT SAFELY ----------
# DejaVuSans-Bold is preinstalled in Colab
FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
font = ImageFont.truetype(FONT_PATH, FONT_SIZE)

# --------- FUNCTION ----------
def draw_text(word, fill, stroke=0):
    img = Image.new("L", (W, H), 0)
    draw = ImageDraw.Draw(img)

    bbox = draw.textbbox((0,0), word, font=font, stroke_width=stroke)
    x = (W - (bbox[2]-bbox[0])) // 2
    y = (H - (bbox[3]-bbox[1])) // 2

    draw.text(
        (x, y),
        word,
        fill=fill,
        font=font,
        stroke_width=stroke,
        stroke_fill=30
    )
    return img

# --------- BUILD IMAGE ----------
near = draw_text(NEAR_WORD, fill=240, stroke=12)
far  = draw_text(FAR_WORD, fill=180).filter(ImageFilter.GaussianBlur(25))

combined = np.clip(
    np.array(near)/255 + np.array(far)/255,
    0, 1
)

final = Image.fromarray((combined * 255).astype("uint8"))
final.show()

# --------- ONE CELL MVP (FONT SAFE) ---------
from PIL import Image, ImageDraw, ImageFont, ImageFilter
import numpy as np
import os, urllib.request

# --------- DOWNLOAD FONT ----------
FONT_URL = "https://github.com/google/fonts/raw/main/ofl/roboto/Roboto-Bold.ttf"
FONT_PATH = "Roboto-Bold.ttf"

if not os.path.exists(FONT_PATH):
    urllib.request.urlretrieve(FONT_URL, FONT_PATH)

# --------- CONFIG ----------
NEAR_WORD = "Month"
FAR_WORD  = "March"

W, H = 1200, 350
FONT_SIZE = 260

# --------- FUNCTION ----------
def draw_text(word, fill, stroke=0):
    img = Image.new("L", (W, H), 0)
    draw = ImageDraw.Draw(img)
    font = ImageFont.truetype(FONT_PATH, FONT_SIZE)

    bbox = draw.textbbox((0,0), word, font=font, stroke_width=stroke)
    x = (W - (bbox[2]-bbox[0])) // 2
    y = (H - (bbox[3]-bbox[1])) // 2

    draw.text(
        (x, y),
        word,
        fill=fill,
        font=font,
        stroke_width=stroke,
        stroke_fill=30
    )
    return img

# --------- BUILD IMAGE ----------
near = draw_text(NEAR_WORD, fill=240, stroke=12)
far  = draw_text(FAR_WORD, fill=180).filter(ImageFilter.GaussianBlur(25))

combined = np.clip(
    np.array(near)/255 + np.array(far)/255,
    0, 1
)

final = Image.fromarray((combined * 255).astype("uint8"))
final.show()

from PIL import Image, ImageDraw, ImageFont, ImageFilter
import numpy as np

# ---------------- CONFIG ----------------
NEAR_WORD = "Month"
FAR_WORD  = "March"

W, H = 1200, 350
FONT_SIZE = 260
FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

# ---------------- FUNCTION ----------------
def draw_text(word, fill, stroke=0):
    img = Image.new("L", (W, H), 0)
    draw = ImageDraw.Draw(img)
    font = ImageFont.truetype(FONT_PATH, FONT_SIZE)

    bbox = draw.textbbox((0,0), word, font=font, stroke_width=stroke)
    x = (W - (bbox[2]-bbox[0])) // 2
    y = (H - (bbox[3]-bbox[1])) // 2

    draw.text(
        (x, y),
        word,
        fill=fill,
        font=font,
        stroke_width=stroke,
        stroke_fill=30
    )
    return img

# ---------------- BUILD IMAGE ----------------
near = draw_text(NEAR_WORD, fill=240, stroke=12)
far  = draw_text(FAR_WORD, fill=180).filter(ImageFilter.GaussianBlur(25))

combined = np.clip(
    np.array(near)/255 + np.array(far)/255,
    0, 1
)

final = Image.fromarray((combined * 255).astype("uint8"))
final.show()

